### ISSUE TITLE
Discord Bot Joining Failure.

### ISSUE THREAD

**Issue by j1tz** [Linesmerrill/police-cad#651] opened 2022-05-16 21:29 UTC
**Describe the bug**
[_A clear and concise description of what the bug is._]

- When a user attempts to invite the LPC discord bot they recieve a error message which includes "This bot can't join more servers as it has not been verified or is requesting gateway intents"

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Go to 'LPC Cad'
2. Click on 'Discord Bot'
3. Scroll down to 'Invite'

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- I expected the discord bot to be able to join my discord server and have access to its features.

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- https://cdn.discordapp.com/attachments/817836599861706792/975871588136271922/Screenshot_2022-05-16_22.25.01.png

**Desktop (please complete the following information):**
 - OS: [Andriod]
 - Browser [chrome]
 - Version [N/A]

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by SowinskiBraeden** [comment] 2022-05-16 21:40
I will be closing this issue, as it is not a bug in the code but the way Discord operates. The bot is currently awaiting verification so it can continue to join more servers. Until then you will need to wait till I announce the bot has been verified and can join more servers.

**Closed** 2022-05-16 21:40 UTC
