### ISSUE TITLE
New feature 

### ISSUE THREAD

**Issue by el-sheriif** [Linesmerrill/police-cad#173] opened 2020-04-22 08:07 UTC
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]
I would like to see a despatch side for the fire EMS and police sides. 

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]
A way to add poeple to calls. Make new calls. 10 codes, and unit lists.  

-

**Comment by Linesmerrill** [comment] 2020-04-25 21:33
Duplicate of: https://github.com/Linesmerrill/police-cad/issues/104

**Closed by Linesmerrill** 2020-04-25 21:33 UTC
