### ISSUE TITLE
Hey Guys as we all know LPS is probably one of the best CADs out there but i was wondering if we could set up a dispatch system so we can have a list of on duty cops and be able to assign the to calls

### ISSUE THREAD

**Issue by officerhowreya** [Linesmerrill/police-cad#194] opened 2020-05-14 20:39 UTC
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment] 2020-05-15 01:49
Hi @officerhowreya! Thank you for the suggestion and the kind words! We are working on this new capability. With Covid we have been a bit behind schedule, so we apologize for any inconvenience. We are working on this and will update when we have a more firm update to release to the public. Thanks!

**Comment by Linesmerrill** [comment] 2020-05-17 15:40
Duplicate of: https://github.com/Linesmerrill/police-cad/issues/30

**Closed by Linesmerrill** 2020-05-17 15:40 UTC
