### ISSUE TITLE
Penal Code For People New To RP

### ISSUE THREAD

**Issue by MakasuSensei** [Linesmerrill/police-cad#322] opened 2020-10-10 22:34 UTC
Hello,

I think it would be a great idea to add penal codes to Lines Police CAD. It would be very useful for many reasons, such as:

-Helping people learn their laws so they don't start an unlawful traffic stop
-Having a specific reason to pull over or arrest someone
-Helping people to get out of an unlawful traffic stop

Thanks for reading,

**Comment by Linesmerrill** [comment] 2020-10-25 15:22
Duplicate of https://github.com/Linesmerrill/police-cad/issues/320

**Closed by Linesmerrill** 2020-10-25 15:22 UTC
