### ISSUE TITLE
Lines Police Mobile

### ISSUE THREAD

**Issue by Allaboutduhmoney** [Linesmerrill/police-cad#254] opened 2020-07-18 09:01 UTC
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Maybe a mobile app so people dont have to switch from FiveM to google chrome or whatever web browser they use.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment] 2020-07-18 14:15
Duplicate of: https://github.com/Linesmerrill/police-cad/issues/245

**Closed by Linesmerrill** 2020-07-18 14:15 UTC
