### ISSUE TITLE
Run report / dispatcher 

### ISSUE THREAD

**Issue by dustincrawford300** [Linesmerrill/police-cad#185] opened 2020-04-30 07:54 UTC
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]
Fill out run reports for fire and ems, and have a dispatcher spot like civ and police something like that for a community 
- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

Fill out run reports for fire and ems, and have a dispatcher spot like civ and police something like that for a community

-

**Comment by dj03** [comment] 2020-04-30 14:39
That's a great idea

**Comment by drgood12** [comment] 2020-05-08 01:11
i also had a similar idea, but went more in depth about it

> That's a great idea

i had a similar idea, but went more into detail about it
https://github.com/Linesmerrill/police-cad/issues/186

**Comment by Linesmerrill** [comment] 2020-05-17 15:44
Duplicate of: https://github.com/Linesmerrill/police-cad/issues/186

**Closed by Linesmerrill** 2020-05-17 15:44 UTC
