### ISSUE TITLE
Community owner tab lock

### ISSUE THREAD

**Issue by Braeden57** [Linesmerrill/police-cad#313] opened 2020-09-22 17:36 UTC
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- The owner of a community should be able to lock tabs. Such as locking the ‘police dashboard’ from any civilians to prevent cheats, trolls etc.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment] 2020-10-25 15:26
Duplicate of https://github.com/Linesmerrill/police-cad/issues/273

**Closed by Linesmerrill** 2020-10-25 15:26 UTC
