### ISSUE TITLE
Calls on dispatch not working 

### ISSUE THREAD

**Issue by jim600** [Linesmerrill/police-cad#327] opened 2020-10-27 12:24 UTC
Hi I been trying to create a call on the dispatch but it’s not show up on the calls area because I’ve click on create a calls type in the information then click on create call add it doesn’t add the call that I’ve created to the calls list is they anyone else get this issue if not then it must be me if it is can someone please have a look at it as soon as they can.

**Comment by Linesmerrill** [comment] 2020-10-27 13:34
Thank you for contacting us! Can you provide us with a bit more information?

- Are you on mobile or computer?
- Were you selecting an officer to assign the call to?
- Did you fill out both the description and call notes before clicking create?

The more details the better our team can quickly reproduce the issue and fix it.

Thanks!

**Comment by jim600** [comment] 2020-10-27 15:07
Hi I’m on mobile when I’m doing it and I was selecting an officer to assign the call to yes I fill out the description and the call notes but it’s not showing up in the calls list where you would change the officers status is

**Comment by Linesmerrill** [comment] 2020-10-27 15:13
Perfect thank you for the additional details.

Our team is actively working on a fix for this. We will update this thread once we have a fix deployed. Thank you!

**Comment by Linesmerrill** [comment] 2020-10-28 02:15
We just pushed out a fix for this. Please let us know if you are still having issues.

**Comment by jim600** [comment] 2020-10-28 13:06
Hi I’ve tried to make a call and is not creating the call on active calls on the dispatch area could you have a another look at this please thanks

**Comment by Linesmerrill** [comment] 2020-10-28 13:35
Yeah we are seeing the same thing. It seems to be intermittently working. Our team is looking into this.

**Comment by Linesmerrill** [comment] 2020-10-29 22:42
Alright what we have found so far is that it seems to be working on Desktop applications, but not on mobile. Our team is working to try to fix this issue and allow mobile devices the ability to create calls.

For now, please try to use a desktop version if available to create calls. On mobile you should be able to view and update/close them.

**Comment by Linesmerrill** [comment] 2020-10-29 23:15
Completed here: https://github.com/Linesmerrill/police-cad/pull/331

**Closed by Linesmerrill** 2020-10-29 23:15 UTC
