### ISSUE TITLE
Can't fill in the case number when giving a ticket or making arrest.

### ISSUE THREAD

**Issue by dreadglitter** [Linesmerrill/police-cad#201] opened 2020-05-22 07:19 UTC
**Describe the bug**
[_A clear and concise description of what the bug is._]
When you go to make a ticket or arrest the case number will not fill or let you type in it.  The select id dose not let you type or select anything.
- 

**To Reproduce**
[_Steps to reproduce the behavior:_]
2. Click on 'Arrest and citation'

**Expected behavior**
[_Be able to put a case number or select a Id _]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**
 - OS: [Apple EL Capitan ]
 - Browser [Chrome]
 - Version [ 81.0.4044.138 ]

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment] 2020-06-01 04:08
Hi @dreadglitter . Thanks for opening this issue. We have investigated the issue is this is what our development team has found out:

> Regarding: "Can't fill in the case number when giving a ticket or making arrest"

Because of the flow of writing citations and arrests, you are required to look up a civilian by name before issuing either of the two actions you are trying to perform. There are some technical reasons behind this as well, but right now we do not allow users to modify the case number and selected ID when submitting a ticket or arrest.

As you can see in the included screenshot below, both the Case No. and Selected ID cannot be modified. The Case No. is a pseudo-random number generated by our severs when you click "Create Citation" after looking up a civilian by name. As for the Selected ID, this is the same ID of the person you lookup by name when clicking "Name Database" and submitting the First, and Last Name (and the Date of Birth if not in a community). This ID cannot be changed as it uniquely defines each civilian in our database.

We do not have any plans to change either of these fields nor make them editable. If that is something you would like to see us add, please submit a feature request and fill out all the proper details so our team can evaluate and discuss this addition.

If you have any other questions please let us know. But as this is currently expected behavior we will be closing this issue. Thank you!

<img width="588" alt="Screen Shot 2020-05-31 at 8 59 01 PM" src="https://user-images.githubusercontent.com/15384983/83374915-ee291580-a381-11ea-8c7a-9bb012545f89.png">

**Closed by Linesmerrill** 2020-06-01 04:08 UTC
