### ISSUE TITLE
dispatch feature

### ISSUE THREAD

**Issue by magana1216** [Linesmerrill/police-cad#104] opened 2020-02-02 00:28 UTC
**Describe the solution you'd like**

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?

this feature is like the police, civi, and fire/ems loggins you provide. but if a dispatcher had their own log in that is suited out for them would be nice.

in a dispatch system you can include
create call
name look up
plate look up
create bolo (car or person)
create warrants. things a dispatcher would do that a police officer wouldn't.

I am unsure if adding this feature can add issues but this is something that most gta cad system do offer.

**Comment by Linesmerrill** [comment] 2020-04-04 18:13
Some additional things we should add to this: (From MauriceS410)

> adding active calls tab and on duty with emergency servicemen/women names on one call
in a community. can see others emergency servicemen/women/"dispatch" notes to relate on. maybe could have feature for the permissions

**Comment by Linesmerrill** [comment] 2020-05-17 15:45
Duplicate of https://github.com/Linesmerrill/police-cad/issues/30

**Closed by Linesmerrill** 2020-05-17 15:45 UTC
