### ISSUE TITLE
More features to licenses

### ISSUE THREAD

**Issue by nashtice** [Linesmerrill/police-cad#168] opened 2020-04-19 10:45 UTC
I would like ( we all would ) just if you could add a feature where you can suspend the licenses of people also i love the work you do on this site 😊 i think these features could make it more realistic 😊

**Comment by Linesmerrill** [comment] 2020-04-21 23:31
Duplicate of https://github.com/Linesmerrill/police-cad/issues/169

**Closed by Linesmerrill** 2020-04-21 23:31 UTC
