### ISSUE TITLE
Dispatch page and an ablily to delete arrest and tickets.

### ISSUE THREAD

**Issue by 1K27** [Linesmerrill/police-cad#160] opened 2020-04-12 16:17 UTC
**Describe the solution you'd like**
I would like a dispatch page and the ability to delete arrests and tickets.
**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for an input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)
The ability for the dispatch to create and assign calls. 
**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?
Unknown.

**Comment by Linesmerrill** [comment] 2020-05-17 15:42
Duplicate of: https://github.com/Linesmerrill/police-cad/issues/30

**Closed by Linesmerrill** 2020-05-17 15:42 UTC
